// AUTO-GENERATED by build_smart_env_config.js. DO NOT EDIT.
import smart_templates from './src/collections/smart_templates.js';
import { SmartTemplate } from './src/items/smart_template.js';
import { render as template_context_builder_component } from './src/components/template_context_builder.js';

export const smart_env_config = {
  collections: {
    smart_templates
  },
  item_types: {
    SmartTemplate
  },
  components: {
    template_context_builder: template_context_builder_component
  }
};
