// AUTO-GENERATED by build_smart_env_config.js. DO NOT EDIT.
import smart_completions from './src/collections/smart_completions.js';
import smart_templates from './src/collections/smart_templates.js';
import { SmartTemplate } from './src/items/smart_template.js';


export const smart_env_config = {
  collections: {
    smart_completions,
    smart_templates
  },
  item_types: {
    SmartTemplate
  },
  components: {

  }
};
