// AUTO-GENERATED by obsidian-smart-env/build/build_env_config.js. DO NOT EDIT.
import smart_templates from './src/collections/smart_templates.js';
import { SmartTemplate } from './src/items/smart_template.js';




export const smart_env_config = {
  collections: {
    smart_templates
  },
  item_types: {
    SmartTemplate
  },
  items: {
    smart_template: { class: SmartTemplate }
  },
  modules: {

  },
  components: {

  },
  actions: {

  }
};
